
import controladores.HabitacionController;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JToggleButton;
import modelos.Habitacion;

public class HabitacionesGrafico extends javax.swing.JInternalFrame {
    HabitacionController habitacion = new HabitacionController();
    ArrayList<Habitacion> listaHabitaciones;
    public HabitacionesGrafico() {
        initComponents();
        botones();
    }
    
    int filas = 20, columnas = 4, largoBtn = 160, anchoBtn = 65;
    int ejeX = 20, ejeY = 20;
    public JToggleButton [][] jTBotones = new JToggleButton[filas][columnas];
    public void botones() {
        listaHabitaciones = habitacion.obtenerHabitaciones();
        int contador = 0;
        for(int  i = 0;  i < filas; i++) {
            for(int j = 0; j < columnas; j++) {
                jTBotones[i][j] = new JToggleButton();
                jTBotones[i][j].setBounds(ejeX, ejeY, largoBtn, anchoBtn);                
                jTBotones[i][j].setText(listaHabitaciones.get(contador).getNombre());
                int disponible = listaHabitaciones.get(contador).getDisponible();
                jTBotones[i][j].setBackground(disponible == 1 ? Color.GREEN : Color.RED);
                panelHabitaciones.add(jTBotones[i][j]);
                ejeX += 160;
                contador++;
                if(contador == listaHabitaciones.size()) {
                    break;
                }
            }
            if(contador == listaHabitaciones.size()) {
                break;
            }
            ejeX = 20;
            ejeY += 70;
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelHabitaciones = new javax.swing.JPanel();
        lblDisponible = new javax.swing.JLabel();
        lblOcupado = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Ocupabilidad");
        setMaximumSize(new java.awt.Dimension(800, 500));
        setPreferredSize(new java.awt.Dimension(800, 500));

        javax.swing.GroupLayout panelHabitacionesLayout = new javax.swing.GroupLayout(panelHabitaciones);
        panelHabitaciones.setLayout(panelHabitacionesLayout);
        panelHabitacionesLayout.setHorizontalGroup(
            panelHabitacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelHabitacionesLayout.setVerticalGroup(
            panelHabitacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 273, Short.MAX_VALUE)
        );

        lblDisponible.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/check-regular-36.png"))); // NOI18N
        lblDisponible.setText("Disponible *puede que este reservada");

        lblOcupado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/block-regular-36.png"))); // NOI18N
        lblOcupado.setText("Ocupada");

        jLabel1.setFont(new java.awt.Font("Ubuntu weight=255", 0, 48)); // NOI18N
        jLabel1.setText("Ocupabilidad");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(lblDisponible)
                        .addGap(18, 18, 18)
                        .addComponent(lblOcupado)
                        .addGap(0, 166, Short.MAX_VALUE))
                    .addComponent(panelHabitaciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(231, 231, 231))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(panelHabitaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDisponible, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblOcupado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblDisponible;
    private javax.swing.JLabel lblOcupado;
    private javax.swing.JPanel panelHabitaciones;
    // End of variables declaration//GEN-END:variables
}
