
import controladores.HabitacionController;
import utils.Validaciones;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.Iterator;
import java.util.Set;
import java.util.List;
import javax.swing.JOptionPane;

import modelos.ReservacionCS;
import modelos.Habitacion;
public class Informacion extends javax.swing.JFrame {
    public static String nombre = "";
    public static String apellido = "";
    public static int adultos = 0;
    public static int ninios = 0;
    public static LocalDate llegada;
    public static LocalDate salida;
    public static Long noches;
    public static ArrayList<Habitacion> habitacionesDisponibles;

    
    public Informacion() {
        initComponents();
        cargarDatos();
        this.setLocationRelativeTo(null);
    }
    
    private void cargarDatos() {
        txtNombre.setText(nombre);
        txtApellido.setText(apellido);
    }
    
    private void abrirHabitaciones() {
        Reservacion reservacion = new Reservacion();
        reservacion.setVisible(true);
        this.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        txtAdultos = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        dpLlegada = new com.github.lgooddatepicker.components.DatePicker();
        dpSalida = new com.github.lgooddatepicker.components.DatePicker();
        jLabel11 = new javax.swing.JLabel();
        txtNinios = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        btnConfirmar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Informacion");
        setMaximumSize(new java.awt.Dimension(723, 549));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 186, 230));

        jLabel19.setText("Titular de la Reserva");
        jLabel19.setFont(new java.awt.Font("Ubuntu weight=255", 1, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(1, 1, 1));

        jLabel22.setText("Nombre (s)");
        jLabel22.setFont(new java.awt.Font("Ubuntu weight=255", 0, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(1, 1, 1));

        txtApellido.setToolTipText("");

        jLabel21.setText("Apellidos");
        jLabel21.setFont(new java.awt.Font("Ubuntu weight=255", 0, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(1, 1, 1));

        jLabel8.setText("¿Cuantos Adultos?");
        jLabel8.setFont(new java.awt.Font("Ubuntu weight=255", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(1, 1, 1));

        jLabel10.setText("Llegada");
        jLabel10.setFont(new java.awt.Font("Ubuntu weight=255", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(1, 1, 1));

        dpLlegada.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                dpLlegadaFocusLost(evt);
            }
        });
        dpLlegada.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                dpLlegadaMouseWheelMoved(evt);
            }
        });
        dpLlegada.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dpLlegadaMouseClicked(evt);
            }
        });
        dpLlegada.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                dpLlegadaPropertyChange(evt);
            }
        });
        dpLlegada.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                dpLlegadaVetoableChange(evt);
            }
        });

        dpSalida.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                dpSalidaFocusLost(evt);
            }
        });
        dpSalida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                dpSalidaMouseReleased(evt);
            }
        });

        jLabel11.setText("Salida");
        jLabel11.setFont(new java.awt.Font("Ubuntu weight=255", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(1, 1, 1));

        txtNinios.setToolTipText("");

        jLabel9.setText("¿Cuantos Niños?");
        jLabel9.setFont(new java.awt.Font("Ubuntu weight=255", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(1, 1, 1));

        jLabel20.setText("Fechas");
        jLabel20.setFont(new java.awt.Font("Ubuntu weight=255", 1, 24)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(1, 1, 1));

        btnConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/check-regular-36.png"))); // NOI18N
        btnConfirmar.setText("Confirmar");
        btnConfirmar.setFont(new java.awt.Font("Ubuntu weight=255", 0, 24)); // NOI18N
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/block-regular-36.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setFont(new java.awt.Font("Ubuntu weight=255", 0, 24)); // NOI18N
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/brush-regular-36.png"))); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.setFont(new java.awt.Font("Ubuntu weight=255", 0, 24)); // NOI18N
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel22)
                            .addComponent(txtNombre)
                            .addComponent(jLabel19)
                            .addComponent(jLabel8)
                            .addComponent(txtAdultos, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20)
                            .addComponent(jLabel10)
                            .addComponent(dpLlegada, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel11)
                            .addComponent(txtApellido)
                            .addComponent(jLabel21)
                            .addComponent(jLabel9)
                            .addComponent(txtNinios, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dpSalida, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE))))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel19)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(jLabel21))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAdultos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNinios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jLabel20)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dpSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dpLlegada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dpLlegadaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dpLlegadaFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_dpLlegadaFocusLost

    private void dpLlegadaMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_dpLlegadaMouseWheelMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_dpLlegadaMouseWheelMoved

    private void dpLlegadaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dpLlegadaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_dpLlegadaMouseClicked

    private void dpLlegadaPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_dpLlegadaPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_dpLlegadaPropertyChange

    private void dpLlegadaVetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_dpLlegadaVetoableChange
        // TODO add your handling code here:
    }//GEN-LAST:event_dpLlegadaVetoableChange

    private void dpSalidaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dpSalidaFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_dpSalidaFocusLost

    private void dpSalidaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dpSalidaMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_dpSalidaMouseReleased

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
        if (txtNombre.getText().trim().length() != 0 || txtApellido.getText().trim().length() != 0 ||
        txtAdultos.getText().trim().length() != 0 || txtNinios.getText().trim().length() != 0 ) {
            Validaciones validacion = new Validaciones();
            validacion.setDias(dpLlegada.getDate(),dpSalida.getDate());
            if(validacion.validarFechaLlegada()){
                JOptionPane.showMessageDialog(null, "La fecha de entrada tiene que ser después de el dia de hoy", "Error", JOptionPane.ERROR_MESSAGE);
            } else if (validacion.validarFechas()) {
                JOptionPane.showMessageDialog(null, "Ingrese una fecha de Salida Correcta", "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                // checar disponibilidad de habitaciones conforme a la fecha
                ReservacionCS newReservacion = new ReservacionCS();
                newReservacion.setLlegada(dpLlegada.getDate());
                newReservacion.setSalida(dpSalida.getDate());
                HabitacionController habitacionC = new HabitacionController();
                ArrayList<String> listHabitaciones = habitacionC.checarDisponiblidad(newReservacion);
                
                Set<String> set = new HashSet<>(listHabitaciones);
                listHabitaciones.clear();
                listHabitaciones.addAll(set);

                ArrayList<Habitacion> habitaciones;
                habitaciones = habitacionC.obtenerHabitaciones();
                habitacionesDisponibles = habitaciones;
                nombre = txtNombre.getText().trim();
                apellido = txtApellido.getText().trim();
                adultos = Integer.parseInt(txtAdultos.getText());
                int niniosResult = Integer.parseInt(txtNinios.getText().trim());
                ninios = (niniosResult < 1) ? 0 : niniosResult;
                llegada = dpLlegada.getDate();
                salida = dpSalida.getDate();
                noches = validacion.obtenerNoches();
                if(listHabitaciones.size() > 0) {

                    String array2[] = new String[listHabitaciones.size()];
                    for(int i = 0; i < array2.length ; i++){
                        String nombre2 = listHabitaciones.get(i);
                        Iterator<Habitacion> it = habitaciones.iterator();
                        while(it.hasNext()) {
                            if(it.next().getNombre().equals(nombre2)) {
                                it.remove();
                            }   
                        }
                    }
                    if(habitaciones.size() > 1) {
                        abrirHabitaciones();
                    } else {
                        JOptionPane.showMessageDialog(null, "No hay habitaciones disponibles en esas fechas", "Error", JOptionPane.ERROR_MESSAGE);
                    }
                } else {
                    abrirHabitaciones();
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Verifique los campos", "Error", JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_btnConfirmarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        Inicio inicio = new Inicio();
        inicio.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLimpiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Informacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Informacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Informacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Informacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Informacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JButton btnLimpiar;
    private com.github.lgooddatepicker.components.DatePicker dpLlegada;
    private com.github.lgooddatepicker.components.DatePicker dpSalida;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtAdultos;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtNinios;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
