
import controladores.HabitacionController;
import controladores.HorarioController;
import java.awt.Image;
import utils.Validaciones;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.Iterator;
import java.util.Set;
import javax.swing.DefaultComboBoxModel;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import modelos.Habitacion;
import modelos.Horario;

public class NuevaReservacion extends javax.swing.JInternalFrame {
    private ArrayList<Habitacion> habitaciones;
    private Long noches;
    private Double total;
    private LocalDate salidaTemp;
    private int idHabitacion = -1;

    public NuevaReservacion() {
        initComponents();
        panelHabitacion.setVisible(false);
        cmbHabitaciones.addItemListener(new ItemListener() {
            public void itemStateChanged(ItemEvent itemEvent) {
                cambiarInformacion(itemEvent.getItem().toString());
            }
        });
    }
    
    public void cargarHabitaciones() {
        String array[] = new String[habitaciones.size()];
        for(int i = 0; i < array.length; i++){
            array[i] = habitaciones.get(i).getNombre();
        }
        DefaultComboBoxModel modelo = new DefaultComboBoxModel(array);
        cmbHabitaciones.setModel(modelo);
        setInformacion(0);
    }
    private void cambiarInformacion(String busqueda) { 
        int i=0;
        while(!habitaciones.get(i).getNombre().equals(busqueda)){
            i++;
        }
        setInformacion(i);
    }
    
    public void setInformacion(int i) {
        String nochesText = noches.toString() + ((noches > 1) ? " noches" : " noche" );
        lblPrecio.setText(habitaciones.get(i).getPrecio().toString());
        Double precio = habitaciones.get(i).getPrecio();
        lblSubText.setText("subtotal " + nochesText);
        total = noches * precio; 
        lblSubtotal.setText(habitaciones.get(i).getPrecio().toString());
        lblTotal.setText(total.toString());
        idHabitacion = habitaciones.get(i).getIdHabitacion();
        ImageIcon icono = new ImageIcon(habitaciones.get(i).getImagen());
        Image imgEscalada = icono.getImage().getScaledInstance(lblImagen.getWidth(),
                lblImagen.getHeight(), Image.SCALE_SMOOTH);
        Icon iconoEscalado = new ImageIcon(imgEscalada);
        lblImagen.setIcon(iconoEscalado);
    }
    
    public void resetearCampos() {
        dpSalida.clear();
        panelHabitacion.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        dpLlegada = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        dpSalida = new com.github.lgooddatepicker.components.DatePicker();
        jLabel11 = new javax.swing.JLabel();
        btnVerificar = new javax.swing.JButton();
        panelHabitacion = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        cmbHabitaciones = new javax.swing.JComboBox<>();
        lblTotal = new javax.swing.JLabel();
        lblSubtotal = new javax.swing.JLabel();
        lblSubText = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        btnReservar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        lblPrecio = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        lblImagen = new javax.swing.JLabel();

        setClosable(true);
        setResizable(true);
        setMaximumSize(new java.awt.Dimension(850, 600));
        setMinimumSize(new java.awt.Dimension(850, 600));
        setPreferredSize(new java.awt.Dimension(850, 650));

        dpLlegada.setPreferredSize(new java.awt.Dimension(850, 600));

        jLabel7.setText("Nuevo Cliente");
        jLabel7.setFont(new java.awt.Font("Ubuntu weight=255", 0, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(1, 1, 1));

        jLabel11.setText("Salida");
        jLabel11.setFont(new java.awt.Font("Ubuntu weight=255", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(1, 1, 1));

        btnVerificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/check-regular-36.png"))); // NOI18N
        btnVerificar.setText("Verificar disponibilidad");
        btnVerificar.setFont(new java.awt.Font("Ubuntu weight=255", 0, 14)); // NOI18N
        btnVerificar.setPreferredSize(new java.awt.Dimension(180, 60));
        btnVerificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerificarActionPerformed(evt);
            }
        });

        jLabel9.setText("Habitaciones Disponibles");
        jLabel9.setFont(new java.awt.Font("Ubuntu weight=255", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(1, 1, 1));

        cmbHabitaciones.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Deluxe Room A", "Deluxe Room B", "Deluxe Room C", "Executive Suite", "Master Suite", "Presidential Suite" }));

        lblTotal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/dollar-regular-36 (2).png"))); // NOI18N
        lblTotal.setText("7,000");
        lblTotal.setFont(new java.awt.Font("Ubuntu weight=255", 0, 36)); // NOI18N
        lblTotal.setForeground(new java.awt.Color(1, 1, 1));

        lblSubtotal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/dollar-regular-36 (2).png"))); // NOI18N
        lblSubtotal.setText("1,400");
        lblSubtotal.setFont(new java.awt.Font("Ubuntu weight=255", 0, 36)); // NOI18N
        lblSubtotal.setForeground(new java.awt.Color(1, 1, 1));

        lblSubText.setText("subtotal");
        lblSubText.setFont(new java.awt.Font("Ubuntu weight=255", 0, 24)); // NOI18N
        lblSubText.setForeground(new java.awt.Color(1, 1, 1));

        jLabel15.setText("Total");
        jLabel15.setFont(new java.awt.Font("Ubuntu weight=255", 0, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(1, 1, 1));

        btnReservar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/check-regular-36.png"))); // NOI18N
        btnReservar.setText("Aceptar");
        btnReservar.setFont(new java.awt.Font("Ubuntu weight=255", 0, 24)); // NOI18N
        btnReservar.setPreferredSize(new java.awt.Dimension(180, 60));
        btnReservar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReservarActionPerformed(evt);
            }
        });

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/block-regular-36.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setFont(new java.awt.Font("Ubuntu weight=255", 0, 24)); // NOI18N
        btnCancelar.setPreferredSize(new java.awt.Dimension(180, 60));
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        lblPrecio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/dollar-regular-36 (2).png"))); // NOI18N
        lblPrecio.setText("1,400");
        lblPrecio.setFont(new java.awt.Font("Ubuntu weight=255", 0, 36)); // NOI18N
        lblPrecio.setForeground(new java.awt.Color(1, 1, 1));

        jLabel19.setText("precio");
        jLabel19.setFont(new java.awt.Font("Ubuntu weight=255", 0, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(1, 1, 1));

        javax.swing.GroupLayout panelHabitacionLayout = new javax.swing.GroupLayout(panelHabitacion);
        panelHabitacion.setLayout(panelHabitacionLayout);
        panelHabitacionLayout.setHorizontalGroup(
            panelHabitacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelHabitacionLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(panelHabitacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel9)
                    .addComponent(cmbHabitaciones, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblImagen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelHabitacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelHabitacionLayout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addGap(61, 61, 61)
                        .addComponent(lblPrecio))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelHabitacionLayout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(61, 61, 61)
                        .addComponent(lblTotal))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelHabitacionLayout.createSequentialGroup()
                        .addComponent(lblSubText)
                        .addGap(61, 61, 61)
                        .addComponent(lblSubtotal))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelHabitacionLayout.createSequentialGroup()
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnReservar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(64, 64, 64))
        );
        panelHabitacionLayout.setVerticalGroup(
            panelHabitacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelHabitacionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelHabitacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelHabitacionLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmbHabitaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblImagen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelHabitacionLayout.createSequentialGroup()
                        .addGap(0, 46, Short.MAX_VALUE)
                        .addGroup(panelHabitacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPrecio)
                            .addComponent(jLabel19))
                        .addGap(18, 18, 18)
                        .addGroup(panelHabitacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSubtotal)
                            .addComponent(lblSubText))
                        .addGap(18, 18, 18)
                        .addGroup(panelHabitacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTotal)
                            .addComponent(jLabel15))
                        .addGap(33, 33, 33)
                        .addGroup(panelHabitacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnReservar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout dpLlegadaLayout = new javax.swing.GroupLayout(dpLlegada);
        dpLlegada.setLayout(dpLlegadaLayout);
        dpLlegadaLayout.setHorizontalGroup(
            dpLlegadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dpLlegadaLayout.createSequentialGroup()
                .addGroup(dpLlegadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dpLlegadaLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(dpLlegadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dpSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)))
                    .addGroup(dpLlegadaLayout.createSequentialGroup()
                        .addGap(278, 278, 278)
                        .addComponent(jLabel7)))
                .addContainerGap(290, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dpLlegadaLayout.createSequentialGroup()
                .addComponent(panelHabitacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dpLlegadaLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnVerificar, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(197, 197, 197))
        );
        dpLlegadaLayout.setVerticalGroup(
            dpLlegadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dpLlegadaLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(dpLlegadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(dpLlegadaLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(39, 39, 39)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dpSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnVerificar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(81, 81, 81)
                .addComponent(panelHabitacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dpLlegada, javax.swing.GroupLayout.PREFERRED_SIZE, 820, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 20, Short.MAX_VALUE)
                .addComponent(dpLlegada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        panelHabitacion.setVisible(false);

    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnVerificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerificarActionPerformed
        // TODO add your handling code here:
        Validaciones validacion = new Validaciones();
        validacion.setDias(LocalDate.now(), dpSalida.getDate());
        if (validacion.validarFechas()) {
            JOptionPane.showMessageDialog(null, "Ingrese una fecha de Salida Correcta", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            salidaTemp = dpSalida.getDate();
            HabitacionController habitacionC = new HabitacionController();
            ArrayList<String> listHabitaciones = habitacionC.checarDisponiblidad(dpSalida.getDate());
            
            Set<String> set = new HashSet<>(listHabitaciones);
            listHabitaciones.clear();
            listHabitaciones.addAll(set);
            
            habitaciones = habitacionC.obtenerHabitaciones();
            
            if(listHabitaciones.size() > 0) {
                String array2[] = new String[listHabitaciones.size()];
                for(int i = 0; i < array2.length ; i++){
                    String nombre2 = listHabitaciones.get(i);
                    Iterator<Habitacion> it = habitaciones.iterator();
                    while(it.hasNext()) {
                        if(it.next().getNombre().equals(nombre2)) {
                            it.remove();
                        }   
                    }
                }
            }
            if(habitaciones.size() > 0) {
                noches = validacion.obtenerNoches();
                panelHabitacion.setVisible(true);
                cargarHabitaciones();
            } else {
                JOptionPane.showMessageDialog(null, "No hay habitaciones disponibles", "Error", JOptionPane.ERROR_MESSAGE);
                panelHabitacion.setVisible(false);
            }
        }
        
    }//GEN-LAST:event_btnVerificarActionPerformed

    private void btnReservarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReservarActionPerformed
        
        Horario nHorario = new Horario();
        nHorario.setEstado("Activo");
        nHorario.setIdHabitacion(idHabitacion);
        nHorario.setLlegada(LocalDate.now());
        nHorario.setSalida(salidaTemp);
        nHorario.setNoches(Integer.parseInt(noches.toString()));
        nHorario.setTotal(total);
        // agregar el total ""pendiente""
        
        HorarioController horarioC = new HorarioController();
        HabitacionController habitacionC = new HabitacionController();
        if(horarioC.crearHorarioHabitacion(nHorario) && habitacionC.cambiarDisponibilidad(idHabitacion)) {
            resetearCampos();
            JOptionPane.showMessageDialog(null, "Habitación reservada, disfrute su estancia", "Success", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, "Ocurrio un error intentelo de nuevo", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_btnReservarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnReservar;
    private javax.swing.JButton btnVerificar;
    private javax.swing.JComboBox<String> cmbHabitaciones;
    private javax.swing.JPanel dpLlegada;
    private com.github.lgooddatepicker.components.DatePicker dpSalida;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JLabel lblSubText;
    private javax.swing.JLabel lblSubtotal;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JPanel panelHabitacion;
    // End of variables declaration//GEN-END:variables
}
